/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as ElectricoRouteImport } from './routes/electrico'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ElectricoIndexRouteImport } from './routes/electrico.index'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'

const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectricoRoute = ElectricoRouteImport.update({
  id: '/electrico',
  path: '/electrico',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectricoIndexRoute = ElectricoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ElectricoRoute,
} as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/electrico': typeof ElectricoRouteWithChildren
  '/nosotros': typeof NosotrosRoute
  '/electrico/': typeof ElectricoIndexRoute
  '/api/public/contact': typeof ApiPublicContactRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/nosotros': typeof NosotrosRoute
  '/electrico': typeof ElectricoIndexRoute
  '/api/public/contact': typeof ApiPublicContactRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/electrico': typeof ElectricoRouteWithChildren
  '/nosotros': typeof NosotrosRoute
  '/electrico/': typeof ElectricoIndexRoute
  '/api/public/contact': typeof ApiPublicContactRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/electrico'
    | '/nosotros'
    | '/electrico/'
    | '/api/public/contact'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/blog' | '/nosotros' | '/electrico' | '/api/public/contact'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/electrico'
    | '/nosotros'
    | '/electrico/'
    | '/api/public/contact'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRoute
  ElectricoRoute: typeof ElectricoRouteWithChildren
  NosotrosRoute: typeof NosotrosRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/electrico': {
      id: '/electrico'
      path: '/electrico'
      fullPath: '/electrico'
      preLoaderRoute: typeof ElectricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/electrico/': {
      id: '/electrico/'
      path: '/'
      fullPath: '/electrico/'
      preLoaderRoute: typeof ElectricoIndexRouteImport
      parentRoute: typeof ElectricoRoute
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ElectricoRouteChildren {
  ElectricoIndexRoute: typeof ElectricoIndexRoute
}

const ElectricoRouteChildren: ElectricoRouteChildren = {
  ElectricoIndexRoute: ElectricoIndexRoute,
}

const ElectricoRouteWithChildren = ElectricoRoute._addFileChildren(
  ElectricoRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRoute,
  ElectricoRoute: ElectricoRouteWithChildren,
  NosotrosRoute: NosotrosRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
